jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - twist/notify:
          webhook: webhook
orbs:
  twist: doist/twist@0.0.1
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build
